spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: "jdbc:h2:tcp://localhost:9090/mem:kartenspiel"
    username: user
    password: 123456789
    driver-class-name: org.h2.Driver
